# Generated by Django 5.1.1 on 2024-10-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
